In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv('questions_dataset_0.2.csv')
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'questions_dataset_0.2.csv'

In [3]:
df.rename(columns={"paper_name":"pdf", "Ответ":"answer"}, inplace=True)

In [13]:
data = df.copy()

In [14]:
data = data[['pdf', 'question', 'answer']]

In [15]:
data.head()

,pdf,question,answer
0,koning-et-al-2021-total-synthesis,What reaction occurs in step 6 of Total Synthe...,In step 6 of Total Synthesis of (-)-Glionitrin...
1,10_1021_acs_joc_0c02350,I need all the compounds that were used in the...,"Lithium bromide\n[Li+].[Br-] \nN,N-dimethylac..."
2,d1ra01912k-2,NaN,NaN
3,d1ra01912k-2,NaN,NaN
4,Die Angewandte Makromolekulare Chemie - 1999 -...,What is happening in diagram 5 ?,The diagram shows the reaction between one mol...

In [16]:
data = data[data.question.isna()==False]
data.head()

,pdf,question,answer
0,koning-et-al-2021-total-synthesis,What reaction occurs in step 6 of Total Synthe...,In step 6 of Total Synthesis of (-)-Glionitrin...
1,10_1021_acs_joc_0c02350,I need all the compounds that were used in the...,"Lithium bromide\n[Li+].[Br-] \nN,N-dimethylac..."
4,Die Angewandte Makromolekulare Chemie - 1999 -...,What is happening in diagram 5 ?,The diagram shows the reaction between one mol...
5,Die Angewandte Makromolekulare Chemie - 1999 -...,Are there any compounds for which IR was taken...,"yes, these are compounds 1a, 1b, 1c, 1d, 1f."
6,hernandez-et-al-2023-alkynyl-halo-aza-prins-an...,What is happening in Scheme 2 ?,The scheme shows the reaction between one mole...

In [17]:
data = data[data.pdf!='molecules-28-02420-v2.pdf']
data.shape

(18, 3)

In [18]:
data

,pdf,question,answer
0,koning-et-al-2021-total-synthesis,What reaction occurs in step 6 of Total Synthe...,In step 6 of Total Synthesis of (-)-Glionitrin...
1,10_1021_acs_joc_0c02350,I need all the compounds that were used in the...,"Lithium bromide\n[Li+].[Br-] \nN,N-dimethylac..."
4,Die Angewandte Makromolekulare Chemie - 1999 -...,What is happening in diagram 5 ?,The diagram shows the reaction between one mol...
5,Die Angewandte Makromolekulare Chemie - 1999 -...,Are there any compounds for which IR was taken...,"yes, these are compounds 1a, 1b, 1c, 1d, 1f."
6,hernandez-et-al-2023-alkynyl-halo-aza-prins-an...,What is happening in Scheme 2 ?,The scheme shows the reaction between one mole...
7,kowalska-et-al-2023-visible-light-promoted-3-2...,How many chiral centers are there in the compo...,3
8,kowalska-et-al-2023-visible-light-promoted-3-2...,Which photocatalyst showed the best results in...,Eosin Y
9,kowalska-et-al-2023-visible-light-promoted-3-2...,Which biologically active compounds are shown ...,"Diaportheone B, Applanatumol Y,Peramivir, Jatr..."
10,kowalska-et-al-2023-visible-light-promoted-3-2...,In which solvent did the reaction of [3+2]-cyc...,Methanol
11,kowalska-et-al-2023-visible-light-promoted-3-2...,What was the diastereomer ratio for product 3a...,10:1 dr
12,kowalska-et-al-2023-visible-light-promoted-3-2...,Name the compounds that reacted [3+2]-cyclopro...,"1ba, 1c, 1g, 1h, 1i"
13,kowalska-et-al-2023-visible-light-promoted-3-2...,What is the IUPAC nomenclature name and the mo...,"(2,2,6,6-tetramethylpiperidin-1-yl)oxidanyl , ..."
14,hernandez-et-al-2023-alkynyl-halo-aza-prins-an...,What is the name of substance number 24a?,3-benzhydrylidene-1-(4-methylphenyl)sulfonyl-2...
15,hernandez-et-al-2023-alkynyl-halo-aza-prins-an...,Why was the yield for 16t greater than for 16b?,"Since at the last step, alkynyl Prints cycliza..."
16,hernandez-et-al-2023-alkynyl-halo-aza-prins-an...,Calculate the molecular weight for compound 19q,332.241
17,hernandez-et-al-2023-alkynyl-halo-aza-prins-an...,Which substituents cause the formation of E- a...,The MeO group in the para position and the Me ...
18,d1ra01912k-2,Which compound has the highest polymerization ...,There is no compound that has the highest poly...
19,d1ra01912k-2,What is rac-(3-Et Ind#)2Zr(CH2Ph)2?,rac-(3-EtInd#)2Zr(CH2Ph)2 is a zirconocene com...

In [20]:
data.pdf = data['pdf'].apply(lambda x: x+'.pdf' if x.endswith('pdf')==False else x)

In [21]:
data.head()

,pdf,question,answer
0,koning-et-al-2021-total-synthesis.pdf,What reaction occurs in step 6 of Total Synthe...,In step 6 of Total Synthesis of (-)-Glionitrin...
1,10_1021_acs_joc_0c02350.pdf,I need all the compounds that were used in the...,"Lithium bromide\n[Li+].[Br-] \nN,N-dimethylac..."
4,Die Angewandte Makromolekulare Chemie - 1999 -...,What is happening in diagram 5 ?,The diagram shows the reaction between one mol...
5,Die Angewandte Makromolekulare Chemie - 1999 -...,Are there any compounds for which IR was taken...,"yes, these are compounds 1a, 1b, 1c, 1d, 1f."
6,hernandez-et-al-2023-alkynyl-halo-aza-prins-an...,What is happening in Scheme 2 ?,The scheme shows the reaction between one mole...

In [22]:
data.pdf.unique()

array(['koning-et-al-2021-total-synthesis.pdf',
       '10_1021_acs_joc_0c02350.pdf',
       'Die Angewandte Makromolekulare Chemie - 1999 - Moszner - Synthesis and polymerisation of new multifunctional urethane.pdf',
       'hernandez-et-al-2023-alkynyl-halo-aza-prins-annulative-couplings.pdf',
       'kowalska-et-al-2023-visible-light-promoted-3-2-cycloaddition-for-the-synthesis-of-cyclopenta-b-chromenocarbonitrile.pdf',
       'd1ra01912k-2.pdf'], dtype=object)

In [23]:
data.to_csv('questions_dataset_0.2_prepared.csv', index=False)

In [7]:
df = pd.read_csv('test_results/gemini-2.0-flash-lite-001_v0.2_only_context.csv')
df.head()

,pdf,question,correct_answer,model_answer,answer_generation_time,Correctness (GEval)_score,Correctness (GEval)_reason
0,..\ChemCoScientist\paper_analysis\papers\konin...,What reaction occurs in step 6 of Total Synthe...,In step 6 of Total Synthesis of (-)-Glionitrin...,In step 6 of Total Synthesis of (-)-Glionitrin...,7.992802,0.7,"The actual output correctly mentions step 6, t..."
1,..\ChemCoScientist\paper_analysis\papers\10_10...,I need all the compounds that were used in the...,"Lithium bromide [Li+].[Br-] N,N-dimethylacet...","I am sorry, I am unable to prepare a table of ...",9.352694,0.0,The actual output does not provide any of the ...
2,..\ChemCoScientist\paper_analysis\papers\Die A...,What is happening in diagram 5 ?,The diagram shows the reaction between one mol...,"In diagram 5, a bifunctional amine methacrylat...",4.705621,0.8,Actual output describes the formation of a bif...
3,..\ChemCoScientist\paper_analysis\papers\Die A...,Are there any compounds for which IR was taken...,"yes, these are compounds 1a, 1b, 1c, 1d, 1f.","Yes, the IR spectra were recorded for pure com...",5.167744,0.9,Actual output provides all expected abbreviati...
4,..\ChemCoScientist\paper_analysis\papers\herna...,What is happening in Scheme 2 ?,The scheme shows the reaction between one mole...,"In Scheme 2, the Aza-Prins synthesis of 2-Quin...",8.624958,0.2,The actual output mentions the Aza-Prins synth...

In [8]:
df.shape

(12, 7)

In [9]:
df['Correctness (GEval)_score'].mean()

np.float64(0.6583333333333333)

In [10]:
df_0 = df[df['Correctness (GEval)_score']<1.0]
df_0

,pdf,question,correct_answer,model_answer,answer_generation_time,Correctness (GEval)_score,Correctness (GEval)_reason
0,..\ChemCoScientist\paper_analysis\papers\konin...,What reaction occurs in step 6 of Total Synthe...,In step 6 of Total Synthesis of (-)-Glionitrin...,In step 6 of Total Synthesis of (-)-Glionitrin...,7.992802,0.7,"The actual output correctly mentions step 6, t..."
1,..\ChemCoScientist\paper_analysis\papers\10_10...,I need all the compounds that were used in the...,"Lithium bromide [Li+].[Br-] N,N-dimethylacet...","I am sorry, I am unable to prepare a table of ...",9.352694,0.0,The actual output does not provide any of the ...
2,..\ChemCoScientist\paper_analysis\papers\Die A...,What is happening in diagram 5 ?,The diagram shows the reaction between one mol...,"In diagram 5, a bifunctional amine methacrylat...",4.705621,0.8,Actual output describes the formation of a bif...
3,..\ChemCoScientist\paper_analysis\papers\Die A...,Are there any compounds for which IR was taken...,"yes, these are compounds 1a, 1b, 1c, 1d, 1f.","Yes, the IR spectra were recorded for pure com...",5.167744,0.9,Actual output provides all expected abbreviati...
4,..\ChemCoScientist\paper_analysis\papers\herna...,What is happening in Scheme 2 ?,The scheme shows the reaction between one mole...,"In Scheme 2, the Aza-Prins synthesis of 2-Quin...",8.624958,0.2,The actual output mentions the Aza-Prins synth...
7,..\ChemCoScientist\paper_analysis\papers\kowal...,In which solvent did the reaction of [3+2]-cyc...,Methanol,The reaction of [3+2]-cycloaddition of 3-Cyano...,10.002731,0.5,The actual output includes more detail than ne...
9,..\ChemCoScientist\paper_analysis\papers\herna...,Why was the yield for 16e greater than for 16d?,"Since at the last step, alkynyl Prints cycliza...",The yield for 16e (54%) was greater than for 1...,8.422009,0.8,Actual output provides correct numeric values ...
10,..\ChemCoScientist\paper_analysis\papers\d1ra0...,Which compound has the highest polymerization ...,There is no compound that has the highest poly...,Based on the context provided in the image:\n*...,8.426443,0.7,The actual output correctly identifies meso-5s...
11,..\ChemCoScientist\paper_analysis\papers\d1ra0...,What is rac-(3-Et Ind#)2Zr(CH2Ph)2?,rac-(3-EtInd#)2Zr(CH2Ph)2 is a zirconocene com...,rac-(3-EtInd#)2Zr(CH2Ph)2 is a yellow solid. I...,10.625991,0.3,The actual output provides detailed NMR data f...

In [11]:
for i, row in df_0.iterrows():
    print('-----------------------')
    print(row['pdf'])
    print(row['question'])
    print(row['correct_answer'])
    print(row['Correctness (GEval)_score'])
    print(row['model_answer'])

-----------------------
..\ChemCoScientist\paper_analysis\papers\koning-et-al-2021-total-synthesis.pdf
What reaction occurs in step 6 of Total Synthesis of (-)-Glionitrin A/B? What reagents were involved in the reaction and what product was obtained? What was the yield obtained?
In step 6 of Total Synthesis of (-)-Glionitrin A/B, a double bond hydroxylation reaction (R)-10a-((((R)-1-(4-Methoxyphenyl)ethyl)thio)-2-methyl-3-methylene-7-nitro-2,3,10,10,10a-tetrahydropyrazino[1,2-a]indole-1,4-dione (in article and SI number 32) occurred to give (3S, 10aR)-3-Hydroxy-3-(hydroxymethyl)-10a-(((R)-1- (4-methoxyphenyl)ethyl)thio)-2-methyl-7-nitro-2,3,10,10,10a-tetrahydropyrazino[1,2-a]indole-1,4-dione (trans isomer, in article number 33, in SI as trans-33) and (3R,10aR)-3-hydroxy-3-(hydroxymethyl)-10a-[(1R)-1-(4-methoxyphenyl)ethyl]sulfanyl-2-methyl-7-nitro-10H-pyrazino[1,2-a]indole-1,4-dione (cis-isomer, in SI as cis-33). The reaction was carried out with 0.1 equiv OsO4 dissolved in 2.5% tert-BuOH, 2.0 equiv NMO, 75:25 acetone and water, respectively, for 16 hours. The yield was 85 percent with a ratio of trans and cis diastereomers 87:13 respectively.
0.7
In step 6 of Total Synthesis of (-)-Glionitrin A/B, diol 33 was dihydroxylated with OsO4/ NMO in acetone/H2O to produce 34 with 85% yield.

-----------------------
..\ChemCoScientist\paper_analysis\papers\10_1021_acs_joc_0c02350.pdf
I need all the compounds that were used in the experiments. Obligatorily I need all results to be in the form of a table of 2 columns where in the first column were the names by IUPAC nomenclature and in the second column in SMILES notation. Don't add it to this list of reaction products for me. Would you be able to do that?
Lithium bromide [Li+].[Br-]   N,N-dimethylacetamide   CC(=O)N(C)C   2-[2-[bis(carboxylatomethyl)azaniumyl]ethyl-(carboxylatomethyl)azaniumyl]acetate  disodium C(C[NH+](CC(=O)[O-])CC(=O)[O-])[NH+](CC(=O)[O-])CC(=O)[O-].[Na+].[Na+]   carbonate  dipotassium C(=O)([O-])[O-].[K+].[K+]  pentane CCCCC  ethoxyethane  CCOCC   sulfate disodium [O-]S(=O)(=O)[O-].[Na+].[Na+]   sodium;chloride   [Na+].[Cl-]   oxidane  O   2-pyridin-2-ylpyridine   C1=CC=NC(=C1)C2=CC=CC=N2 argon [Ar]   potassium;dihydrogen phosphate   OP(=O)(O)[O-].[K+]   hexane CCCCCC  dichloromethane C(Cl)Cl   N,N-dimethylformamide  CN(C)C=O   1-azabicyclo[2.2.2]octane  C1CN2CCC1CC2   morpholine C1COCCN1   1-bromo-4-(trifluoromethyl)benzene   C1=CC(=CC=C1C(F)(F)F)Br   trichloro(deuterio)methane   [2H]C(Cl)(Cl)Cl   cyclohexanamine   C1CCC(CC1)N   hexan-1-amine  CCCCCCN    N-methylmethanamine;hydrochloride   CNC.Cl   methyl 2-aminoacetate;hydrochloride    COC(=O)CN.Cl   bromobenzene C1=CC=C(C=C1)Br  4-bromobenzonitrile C1=CC(=CC=C1C#N)Br   4-bromobenzoate  C1=CC(=CC=C1C(=O)[O-])Br  2-bromonaphthalene  C1=CC=C2C=C(C=CC2=C1)Br   1-bromo-2-methylbenzene   CC1=CC=CC=C1Br   3-bromopyridine   C1=CC(=CN=C1)Br   ethyl acetate   CCOC(=O)C   ethoxyethane   CCOCC   1-bromo-3-methoxybenzene   COC1=CC(=CC=C1)Br  benzoic acid C1=CC=C(C=C1)C(=O)O   (2S)-5-[(2-methylpropan-2-yl)oxy]-2-[(2-methylpropan-2-yl)oxycarbonylamino]-5-oxopentanoic acid  CC(C)(C)OC(=O)CC[C@@H](C(=O)O)NC(=O)OC(C)(C)C dimethyl butanedioate  COC(=O)CCC(=O)OC   sodium;acetate   CC(=O)[O-].[Na+]   (2S)-1-[(2-methylpropan-2-yl)oxycarbonyl]pyrrolidine-2-carboxylic acid   CC(C)(C)OC(=O)N1CCC[C@H]1C(=O)O  phenylmethanol C1=CC=C(C=C1)CO   cyclohexanol  C1CCC(CC1)O   propan-2-ol   CC(C)O   hexan-1-ol   CCCCCCO   methyl 4-bromobenzoate   COC(=O)C1=CC=C(C=C1)Br   3-bromopyridine C1=CC(=CN=C1)Br   Acetonitrile CC#N   4-tert-butyl-2-(4-tert-butylpyridin-2-yl)pyridine   CC(C)(C)C1=CC(=NC=C1)C2=NC=CC(=C2)C(C)(C)C  tetrabutylazanium;hexafluorophosphate   CCCC[N+](CCCC)(CCCC)CCCC.F[P-](F)(F)(F)(F)F
0.0
I am sorry, I am unable to prepare a table of the compounds in the experimental section with IUPAC names and SMILES notations. The provided text contains many compounds, but it does not provide a full list of all compounds by IUPAC nomenclature with their SMILES notations.

-----------------------
..\ChemCoScientist\paper_analysis\papers\Die Angewandte Makromolekulare Chemie - 1999 - Moszner - Synthesis and polymerisation of new multifunctional urethane.pdf
What is happening in diagram 5 ?
The diagram shows the reaction between one molecule of TMXDI ( 1,3-bis(2-isocyanatopropan-2-yl)benzene ) and two molecules of ( benzyl 2-(hydroxymethyl)prop-2-enoate ) in the presence of DBTDO ( dibutyltin dioctanoate ) and the release of 2 molecules of CO2 (carbon dioxide, carbon dioxide) and one molecule of benzyl 2-[[2-[[2-[3-[2-[2-(2-phenylmethoxycarbonylprop-2-enylamino)propan-2-yl]phenyl]propan-2-ylamino]methyl]prop-2-enoate
0.8
In diagram 5, a bifunctional amine methacrylate was formed by the elimination of carbon dioxide from the intermediary formed adduct of benzyl a-hydroxymethylacrylate and TMXDI (Scheme 5).

-----------------------
..\ChemCoScientist\paper_analysis\papers\Die Angewandte Makromolekulare Chemie - 1999 - Moszner - Synthesis and polymerisation of new multifunctional urethane.pdf
Are there any compounds for which IR was taken? If there are, write me the abbreviations of those compounds that were taken in pure form.
yes, these are compounds 1a, 1b, 1c, 1d, 1f.
0.9
Yes, the IR spectra were recorded for pure compounds.

The abbreviations are:
*   1a
*   1b
*   1c
*   1d
*   1e
*   1f

-----------------------
..\ChemCoScientist\paper_analysis\papers\hernandez-et-al-2023-alkynyl-halo-aza-prins-annulative-couplings.pdf
What is happening in Scheme 2 ?
The scheme shows the reaction between one molecule of 3-Buten-1-amine and one molecule of Methyl (2-formylphenyl)carbamate to form (10R)-10-acetyl-5,8,9,9,10,11,11a-hexahydropyrido[1,2-c]quinazolin-6-one. The reaction takes place in the presence of acetic acid at 160 ℃
0.2
In Scheme 2, the Aza-Prins synthesis of 2-Quinazolines is shown.
N-acyliminium electrophile intermediate 10 is used with primary amine 12 and benzaldehyde derivative 13 to produce a 2-Quinazoline 14.

-----------------------
..\ChemCoScientist\paper_analysis\papers\kowalska-et-al-2023-visible-light-promoted-3-2-cycloaddition-for-the-synthesis-of-cyclopenta-b-chromenocarbonitrile.pdf
In which solvent did the reaction of [3+2]-cycloaddition of 3-Cyanochromone 1a and N-Cyclopropyloaniline 2a produce the lowest yield?
Methanol
0.5
The reaction of [3+2]-cycloaddition of 3-Cyanochromone 1a and N-Cyclopropyloaniline 2a produced the lowest yield (26%) in CH2Cl2.

-----------------------
..\ChemCoScientist\paper_analysis\papers\hernandez-et-al-2023-alkynyl-halo-aza-prins-annulative-couplings.pdf
Why was the yield for 16e greater than for 16d?
Since at the last step, alkynyl Prints cyclization occurs, in which the nucleophile participates in the form of a Halogenide.The yield of 16e in this reaction will be higher due to the presence of iodide, which is more nucleophilic than bromine.
0.8
The yield for 16e (54%) was greater than for 16d (30%) because the reaction of benzaldehyde 13a (16e) uses sodium iodide, which is a cheaper and greener alternative, and gives better results (Table 1, entry 4). The compound 16d uses sodium bromide.

-----------------------
..\ChemCoScientist\paper_analysis\papers\d1ra01912k-2.pdf
Which compound has the highest polymerization activity over the entire temperature range? And which one is the lowest at 80 degrees?
There is no compound that has the highest polymerization activity. However, meso-5sMAO has the highest activity in the range of 60-90 degrees Celsius. But the lowest activity at 80 degrees is observed on 1sMAO, as in the control. If we talk about the zirconocenes, then for musso- 2 sMA.
0.7
Based on the context provided in the image:
*   **Highest polymerization activity over the entire temperature range:** meso-5SMAO
*   **Lowest polymerization activity at 80 degrees:** meso-2SMAO
-----------------------
..\ChemCoScientist\paper_analysis\papers\d1ra01912k-2.pdf
What is rac-(3-Et Ind#)2Zr(CH2Ph)2?
rac-(3-EtInd#)2Zr(CH2Ph)2 is a zirconocene complex, an organometallic compound consisting of a tetravalet zirconium ion [Zr-4], two 3-ethyl-2,4,5,6,7-pentamethyl-1H-inden-1-ide CCc1c(C)[cH-]c2c(C)c(C)c(C)c(C)c12 and two methanidylbenzene [CH2-]c1ccccc1
0.3
rac-(3-EtInd#)2Zr(CH2Ph)2 is a yellow solid. Its ¹H NMR spectrum (chloroform-d₁, 400 MHz, 298 K) δ (ppm) : 7.08 (m-Ph-H, 4H, dd, JHH = 7.3, 7.4 Hz), 6.80 (p-Ph-H, 2H, t, JHH = 7.3 Hz), 6.62 (o-Ph-H, 4H, d, ³JHH = 7.4 Hz), 4.91 (Ind-H, 2H, s), 2.76 (Ind-CH2-CH3, 2H, dq, JHH = 14.8 Hz, ³JHH = 7.4 Hz), 2.51 (Ind-CH3, 6H, s), 2.45 (Ind-CH2-CH3, 2H, dq, JHH = 14.8 Hz, ³JHH = 7.4 Hz), 2.28 (Ind-CH3, 6H, s), 2.23 (Ind-CH3, 6H, s), 2.01 (Ind-CH3, 6H, s), 1.82 (Ind-CH3, 6H, s), 0.99 (Ind-CH2-CH3, 6H, t, ³JHH = 7.4 Hz), 0.87 (Zr-CH2-Ph, 2H, d, ²JHH = 11.2 Hz), 0.67 (Zr-CH2-Ph, 2H, d, ²JHH = 11.2 Hz). Its 13C{¹H} NMR (chloroform-d₁, 101 MHz, 298 K) δ (ppm): 152.8 (Zr-CH2-Ph), 133.3 (Ind), 131.0 (Ind), 128.3 (Ind), 127.9 (Ind), 127.8 (Ind), 127.6 (m-Ph), 127.1 (o-Ph), 126.4 (Ind), 123.2 (Ind), 121.0 (p-Ph), 119.8 (Ind), 100.8 (Ind-H), 66.0 (Zr-CH2-Ph), 21.6 (Ind-CH2-CH3), 17.1 (Ind-CH3), 16.8 (Ind-CH3).